services:
  check:
    build: .      # 本地拉取镜像
    command: healthcheck.py --interval 300
    volumes:
      - .:/app
    restart: unless-stopped

  web:
    build: .
    ports:
      - "5000:5000"
    command: web.py
    volumes:
      - .:/app
    restart: unless-stopped
